name: Publish package to pub.dev
on:
  push:
    branches:   
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - uses: actions/checkout@master
      - name: Update plugin version
        if: startsWith(github.event.commits[0].message, 'library file version')
        run: |
          version=$(grep -A 0 'version:' pubspec.yaml | sed 's/^.*: //')
          lastNumber=$(echo $version | grep -Eo '[0-9]+$')
          lastNumber=$((lastNumber+1))
          newVersion=$(echo "${version%.*}.${lastNumber}")
          sed -i "s/^version: .*$/version: $newVersion/" pubspec.yaml
      - name: Commit changes
        if: startsWith(github.event.commits[0].message, 'library file version')
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pubspec.yaml
          git commit -m "Update version ${{newVersion}}" -a
          git push origi master
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      - name: Setup credentials
        if: startsWith(github.event.commits[0].message, 'Release')
        run: |
          mkdir -p ~/.pub-cache
          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "accessToken":"${{ secrets.OAUTH_ACCESS_TOKEN }}",
            "refreshToken":"${{ secrets.OAUTH_REFRESH_TOKEN }}",
            "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
            "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
            "expiration": 1570721159347
          }
          EOF
      - name: Publish package
        if: startsWith(github.event.commits[0].message, 'Release')
        run: pub publish -f